/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Song = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'duration' : IDL.Nat,
  'thumbnailUrl' : IDL.Text,
  'artist' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Playlist = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'songs' : IDL.Vec(Song),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addSongToPlaylist' : IDL.Func([IDL.Text, Song], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrUpdatePlaylist' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deletePlaylist' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLikedSongs' : IDL.Func([], [IDL.Vec(Song)], ['query']),
  'getRecentlyPlayed' : IDL.Func([], [IDL.Vec(Song)], ['query']),
  'getUserPlaylists' : IDL.Func([], [IDL.Vec(Playlist)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordRecentlyPlayed' : IDL.Func([Song], [], []),
  'removeSongFromPlaylist' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'toggleLikeSong' : IDL.Func([Song], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Song = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'duration' : IDL.Nat,
    'thumbnailUrl' : IDL.Text,
    'artist' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Playlist = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'songs' : IDL.Vec(Song),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addSongToPlaylist' : IDL.Func([IDL.Text, Song], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrUpdatePlaylist' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deletePlaylist' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLikedSongs' : IDL.Func([], [IDL.Vec(Song)], ['query']),
    'getRecentlyPlayed' : IDL.Func([], [IDL.Vec(Song)], ['query']),
    'getUserPlaylists' : IDL.Func([], [IDL.Vec(Playlist)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordRecentlyPlayed' : IDL.Func([Song], [], []),
    'removeSongFromPlaylist' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'toggleLikeSong' : IDL.Func([Song], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };